### ISSUE TITLE
Changing the polling rate of hardware inputs

### ISSUE THREAD

**Issue by dustyirwin** [aviks/GameZero.jl#26]
Hi all, is there a way to change the polling rate of the mouse/keyboard inputs? I tried looking in `event.jl`, but I'm not too familiar with how events are scheduled...

**Comment by aviks** [comment]
So the polling for events occurs inbetween frames (SDL2 queues them up). So if you find inputs are slow, it's likely only because your frame takes too long to render or update. 

All the logic for the polling is in the mainloop function: https://github.com/aviks/GameZero.jl/blob/master/src/GameZero.jl#L79

**Comment by dustyirwin** [comment]
Thanks for the info, my problem is that the events are happening too fast (a good problem to have!) and executing several commands before the key is released--even on a very short tap. 

Looking at the code, I could modify handleEvents! to perhaps accept and return the timer and check the elapsed duration before continuing the loop, but would that slow down the whole game?

**Comment by dustyirwin** [comment]
After reviewing my code, I've decided that changing the polling rate isn't a good way to solve my problem. Instead, I've changed from executing functions directly via mouse/keyboard inputs, they now switch flags on/off and letting the game engine execute the functions based on those flags to control actor animation, destruction, etc.
